# Exercise - The Basics - Pixels

## Exercise 1

1. What is the bit sequence of the pixel value 150?
2. In a 100x100 grayscale image, each pixel is represented by 256 gray levels. How much memory (bytes) is required to store the image?
3. In a 100 x 100 gray-scale image each pixel is represented by 4 gray levels. How much memory (bytes) is required to store the image?
4. We want to photograph an object which is 1m tall and 10m away from the camera. The height of the object in the image should be 1mm. What should the focal length (f) be? (we assume that the object is in focus at the focal point, hence f=b)

## ANSWERS:

1):

1001 0110


2):

100 * 100 * 1 = 10,000
10.000 Bytes, or 10kB

3):

100 * 100 * 1 = 10,000
One byte is the minimum memory a pixel can take, so in this case, each pixel still requires one byte, they just only use the first two bits.
10.000 Bytes, or 10kB

4):

G = 1m
g = 10m
B = 0.001m

f=b

(b/B)=(g/G)

(f/B)=(g/G)

f=(g/G)*B

((10/1)*0.001) m = 0.01 m = 10 mm

## Exercise 2

Mick is 2m tall and standing 5m from a camera. The camera’s focal length is 5mm. The camera image has a size of 640x480 pixels.
The camera has a 1/2” CCD chip:

![CCD chip image](extra\billede.png)

1. A focused image of Mick is formed inside the camera. At which distance from the lens?
2. How tall (in mm) will Mick be on the CCD-chip?
3. How tall (in pixels) will Mick be on the CCD-chip?
4. What is the field-of-view of the camera?

## ANSWERS:

G = 2 m
g = 5 m
f = 5 mm = 0.005 m
img_res = 640x480

### 1):
Since Mick is a few meters away from the camera, (1/g) has virtually no effect, and thus we get b=f
The focused image is therefore formed 5 mm from the lens.

### 2):
(b/B) = (g/G)
B = (b*G)/g

As mentioned in (1), b = f

B = (f*G)/g

(5mm * 2,000 mm) / 5,000 mm = 2 mm

### 3):
The CCD chip is 4.8 mm tall

The ratio between 2 and 4,8 = 0.4166

Since there are 480 pixels in the image, Mick will be 200 mm tall.

### 4):
The field of view consists of a horizontal part and a vertical part.

FOV_x = 2 * atan((6.4/2)/f) = 1.14 rad

FOV_y = 2 * atan((4.8/2)/f) = 0.89 rad


## Exercise 3

1. Install OpenCV
2. Make a program which loads and displays an image using OpenCV
3. Download a picture. Make a program which loops over each pixel and prints its value, row by row.

In [1]:
import cv2 as cv2

img = cv2.imread("exercise_materials\paper.jpg")

cv2.imshow("", img)

cv2.waitKey(0)

97

In [10]:
import cv2

img = cv2.imread("exercise_materials\paper.jpg")

shape = img.shape
height = shape[0]
width = shape[1]

for y in range(width):
    for x in range(height):
        print(img[x,y])

549
[154 154 154]
[154 154 154]
[154 154 154]
[154 154 154]
[154 154 154]
[154 154 154]
[154 154 154]
[154 154 154]
[152 152 152]
[156 156 156]
[157 157 157]
[154 154 154]
[153 153 153]
[154 154 154]
[154 154 154]
[152 152 152]
[144 144 144]
[139 139 139]
[140 140 140]
[150 150 150]
[157 157 157]
[152 152 152]
[138 138 138]
[127 127 127]
[125 125 125]
[141 141 141]
[155 155 155]
[156 156 156]
[150 150 150]
[148 148 148]
[151 151 151]
[155 155 155]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[149 149 149]
[149 149 149]
[149 149 149]
[148 148 148]
[148 148 148]
[148 148 148]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[150 150 150]
[152 152 152]
[147 147 147]
[145 145 145]
[143 143 143]
[141 141 141]
[146 146 146]
[147 147 147]
[139 139 139]
[146 146 146]
[148 148 148]
[153 153 153]
[153 153 153]
[142 142 142]
[125 125 125]
[118 118 118]
[1

## Exercise 4

1. Design an algorithm (on paper), which can do histogram stretching.
2. Use [ImageJ](https://imagej.nih.gov/ij/download.html) to play around with gray level mapping, histograms, and thresholding.
3. Use ImageJ to improve the quality of the image [enhance_me.jpg](exercise_materials\enhance-me.jpg)
4. Use ImageJ to improve the image [dots.jpg](exercise_materials\dots.jpg) so that only 28 non-connected dots remain.
5. Use ImageJ to improve the image paper.jpg so that the text is black and the rest is white. Consider subtracting the mean of the image before thresholding.
6. How will the Threshold-algorithm output look if two threshold values are used instead of just one?
7. Is it wise to have a binary image consisting of 0s and 1s?

In [ ]:
import cv2
import numpy as np

img = cv2.imread("exercise_materials\paper.jpg", 0)
hist = cv2.calcHist(img, [0], None, [256], [0, 256])
f1 = 256
f2 = 0

for i in range(hist.size):
    if hist[i] != 0:
        f1 = i
        break

for i in range(hist.size):
    if hist[::-1][i] != 0:
        f2 = 256 - i
        break

new_img = np.zeros((img.shape[0], img.shape[1]))

for y in range(new_img.shape[1]):
    for x in range(new_img.shape[0]):
        new_img[x,y] = (255/(f2-f1))*(img[x,y]-f1)

new_hist = np.histogram(new_img.ravel(), 256, [0, 256])

cv2.imshow("", new_img)

cv2.waitKey(0)

## Exercise 5

1. Use OpenCV to load and display a color image
2. Convert it to grayscale using nested loops
3. Convert it to grayscale using matrix multiplication
4. Convert it to grayscale using the built-in OpenCV function

In [18]:
import cv2
import numpy as np

img = cv2.imread("Lenna.png")
height = img.shape[0]
width = img.shape[1]

for_img = np.zeros((height, width), np.uint8)

for x in range(height):
    for y in range(width):
        for_img[x,y] = (img[x, y, 0]*0.333+img[x, y, 1]*0.333+img[x, y, 2]*0.333)

# matrix_img = np.matmul(img, np.array([1, 1, 0.33])) # Not working



cv_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)



cv2.imshow("Original", img)
cv2.imshow("Nested For Loop", for_img)
# cv2.imshow("Matrix Multiplication", matrix_img)
cv2.imshow("OpenCV Conversion", cv_img)

cv2.waitKey(0)